In [3]:
import numpy as np

In [4]:
simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [5]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(5,23,0.1)

array([ 5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,
        6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,
        7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,
        8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,
        9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4,
       10.5, 10.6, 10.7, 10.8, 10.9, 11. , 11.1, 11.2, 11.3, 11.4, 11.5,
       11.6, 11.7, 11.8, 11.9, 12. , 12.1, 12.2, 12.3, 12.4, 12.5, 12.6,
       12.7, 12.8, 12.9, 13. , 13.1, 13.2, 13.3, 13.4, 13.5, 13.6, 13.7,
       13.8, 13.9, 14. , 14.1, 14.2, 14.3, 14.4, 14.5, 14.6, 14.7, 14.8,
       14.9, 15. , 15.1, 15.2, 15.3, 15.4, 15.5, 15.6, 15.7, 15.8, 15.9,
       16. , 16.1, 16.2, 16.3, 16.4, 16.5, 16.6, 16.7, 16.8, 16.9, 17. ,
       17.1, 17.2, 17.3, 17.4, 17.5, 17.6, 17.7, 17.8, 17.9, 18. , 18.1,
       18.2, 18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. , 19.1, 19.2,
       19.3, 19.4, 19.5, 19.6, 19.7, 19.8, 19.9, 20

In [12]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [20]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [22]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [23]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [25]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [34]:
np.random.rand(2,4)

array([[0.6610126 , 0.83887062, 0.6260867 , 0.82168702],
       [0.78482255, 0.74183306, 0.86968783, 0.61017482]])

In [28]:
np.random.randn(2,4)

array([[ 0.28843049,  2.7568804 ,  0.43483411, -0.02083209],
       [-0.85022579, -1.09042717, -1.48399653,  1.58938057]])

In [46]:
np.random.rand(2,7)

array([[0.5491188 , 0.4660072 , 0.90819555, 0.26164513, 0.2707727 ,
        0.45838358, 0.4150686 ],
       [0.90829461, 0.37480655, 0.82477144, 0.91734068, 0.27532998,
        0.55897827, 0.57569803]])

In [47]:
np.random.randint(2,5)

2

In [49]:
np.random.randint(20,56,100)

array([39, 43, 38, 29, 52, 32, 41, 37, 44, 33, 37, 54, 38, 21, 27, 48, 27,
       31, 32, 20, 39, 43, 37, 46, 30, 53, 50, 51, 30, 29, 32, 32, 28, 21,
       49, 34, 45, 38, 32, 33, 54, 23, 22, 47, 35, 54, 34, 46, 45, 49, 27,
       31, 55, 31, 50, 47, 51, 51, 45, 51, 46, 25, 25, 32, 27, 25, 55, 54,
       29, 32, 54, 51, 46, 28, 33, 33, 21, 53, 32, 36, 44, 41, 36, 39, 34,
       42, 54, 28, 27, 35, 22, 46, 34, 23, 28, 47, 30, 21, 51, 24])

In [50]:
np.random.randint(50,52,40)

array([50, 51, 50, 50, 51, 50, 50, 50, 50, 51, 51, 51, 51, 51, 51, 50, 50,
       51, 51, 51, 51, 51, 51, 51, 50, 51, 50, 50, 50, 50, 51, 51, 51, 50,
       51, 51, 50, 50, 50, 50])

In [52]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [65]:
rand_array=np.random.randint(0,10,5)
rand_array

array([6, 6, 6, 7, 9])

In [66]:
sample_array.min()

2

In [67]:
sample_array.argmin()

0

In [68]:
sample_array.max()

19

In [69]:
sample_array.argmax()

17

In [70]:
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [71]:
sample_array.dtype

dtype('int32')

In [74]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
a=np.random.rand(2,3)
a

array([[0.93525919, 0.29654108, 0.69403065],
       [0.31539079, 0.91168605, 0.50113252]])

In [77]:
a.T

array([[0.93525919, 0.31539079],
       [0.29654108, 0.91168605],
       [0.69403065, 0.50113252]])

In [78]:
s=np.arange(10,22)
s

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [81]:
s=s.reshape(4,3)
s

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [84]:
s[4:]

array([], shape=(0, 3), dtype=int32)

In [86]:
s[1]=400
s

array([[ 10,  11,  12],
       [400, 400, 400],
       [ 16,  17,  18],
       [ 19,  20,  21]])

In [88]:
m=np.arange(10,21)
m

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [89]:
m[0:10] #10th index not included

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [91]:
subset_m=m[0:7] #7th index not included
subset_m

array([10, 11, 12, 13, 14, 15, 16])

In [93]:
subset_m[:]=1002 #Replacing all elements with 1002
subset_m

array([1002, 1002, 1002, 1002, 1002, 1002, 1002])

In [94]:
#Two Dimensional Array
